version: 2.1
jobs:
  run-test:
      docker:
      - image: circleci/node:18
      
    # Steps to the job
   steps:
      - checkout
      - run: npm ci
  test:
    docker:
      - image: circleci/node:18-browsers
      - run:
          name: Run tests
          command: npm run test:master
# Invoke jobs via workflows
workflows:
  run-test-workflow:
    jobs:
      - run-test